/**
 * Contradiction Scan — pair generator + scan driver (issue #520).
 *
 * Nightly cron that pairs semantically-similar active memories within
 * the same namespace, sends candidate pairs to the LLM-as-judge
 * contradiction classifier, and drops contradicting pairs into a
 * review queue for user resolution.
 *
 * Pair generation (cheap pre-filter):
 *   1. Find candidate peers via embedding cosine >= similarityFloor.
 *   2. Restrict to pairs sharing at least one entityRef OR overlapping
 *      topic tokens >= topicOverlapFloor.
 *   3. Skip pairs already judged independent/both-valid within cooldown.
 *   4. Cap per-run work at maxPairsPerRun.
 */

import type { StorageManager } from "../storage.js";
import type { PluginConfig, MemoryFile, MemoryStatus } from "../types.js";
import type { SemanticDedupLookup } from "../dedup/semantic.js";
import { log } from "../logger.js";
import { judgeContradictionPairs, type ContradictionJudgeInput } from "./contradiction-judge.js";
import {
  writePairs,
  listPairs,
  isCoolingDown,
  computePairId,
  type ContradictionPair,
} from "./contradiction-review.js";
import type { LocalLlmClient } from "../local-llm.js";
import type { FallbackLlmClient } from "../fallback-llm.js";

// ── Types ──────────────────────────────────────────────────────────────────────

/** The set of statuses that represent "live" memories eligible for scanning. */
export const ACTIVE_STATUSES: Set<MemoryStatus> = new Set(["active"]);

/** High-value taxonomy buckets to scan. */
const SCAN_CATEGORIES = new Set([
  "decision",
  "principle",
  "rule",
  "entity",
  "fact",
  "preference",
]);

export interface ScanResult {
  /** Total active memories scanned. */
  scanned: number;
  /** Candidate pairs generated by the pre-filter. */
  candidates: number;
  /** Pairs sent to judge. */
  judged: number;
  /** Pairs written to review queue. */
  queued: number;
  /** Pairs skipped due to cooldown. */
  cooledDown: number;
  /** Total wall-clock time in ms. */
  elapsedMs: number;
}

export interface ScanDependencies {
  storage: StorageManager;
  config: PluginConfig;
  memoryDir: string;
  /** Pre-built embedding lookup. When provided, used as-is for Strategy 3. */
  embeddingLookup?: SemanticDedupLookup;
  /**
   * Factory to build a namespace-scoped embedding lookup.
   * When provided, takes precedence over `embeddingLookup`.
   * The scan driver passes its own `storage` so the lookup queries the correct index.
   */
  embeddingLookupFactory?: (storage: StorageManager) => SemanticDedupLookup | undefined;
  localLlm: LocalLlmClient | null;
  fallbackLlm: FallbackLlmClient | null;
  namespace?: string;
}

// ── Main scan driver ───────────────────────────────────────────────────────────

/**
 * Run a contradiction scan over the memory corpus.
 *
 * This is the entry point called by the nightly cron and by the CLI.
 */
export async function runContradictionScan(deps: ScanDependencies): Promise<ScanResult> {
  const startTime = Date.now();
  const { storage, config, memoryDir, embeddingLookup, embeddingLookupFactory, localLlm, fallbackLlm, namespace } = deps;
  const scanConfig = config.contradictionScan;

  // Prefer the factory (which uses the scan's own storage for correct namespace scoping)
  // over a pre-built lookup (which may use default-namespace storage).
  const scopedEmbeddingLookup = embeddingLookupFactory
    ? embeddingLookupFactory(storage)
    : embeddingLookup;

  if (!scanConfig.enabled) {
    log.info("[contradiction-scan] disabled by config");
    return { scanned: 0, candidates: 0, judged: 0, queued: 0, cooledDown: 0, elapsedMs: 0 };
  }

  // 1. Load active memories in scan categories
  const memories = await loadEligibleMemories(storage, namespace);
  log.info("[contradiction-scan] loaded %d eligible memories", memories.length);

  if (memories.length < 2) {
    return { scanned: memories.length, candidates: 0, judged: 0, queued: 0, cooledDown: 0, elapsedMs: Date.now() - startTime };
  }

  // 2. Load existing review pairs for cooldown checking
  const existingPairs = listPairs(memoryDir, { filter: "all", namespace, limit: 10000 }).pairs;
  const existingMap = new Map<string, ContradictionPair>();
  for (const p of existingPairs) {
    existingMap.set(p.pairId, p);
  }

  // 3. Generate candidate pairs
  const candidates = await generatePairs(memories, existingMap, scanConfig, scopedEmbeddingLookup);
  const cooledDown = candidates.skipped;
  log.info("[contradiction-scan] generated %d candidates (%d cooled down)", candidates.pairs.length, cooledDown);

  if (candidates.pairs.length === 0) {
    return {
      scanned: memories.length,
      candidates: 0,
      judged: 0,
      queued: 0,
      cooledDown,
      elapsedMs: Date.now() - startTime,
    };
  }

  // 4. Cap at maxPairsPerRun (deterministic selection by pairId)
  const capped = candidates.pairs
    .sort((a, b) => computePairId(a.idA, a.idB).localeCompare(computePairId(b.idA, b.idB)))
    .slice(0, scanConfig.maxPairsPerRun);

  // 5. Build judge inputs
  const judgeInputs: ContradictionJudgeInput[] = capped.map((pair) => ({
    memoryIdA: pair.idA,
    memoryIdB: pair.idB,
    textA: pair.textA,
    textB: pair.textB,
    categoryA: pair.categoryA,
    categoryB: pair.categoryB,
  }));

  // 6. Send to judge (per-scan cache avoids module-level singleton leak)
  const scanCache = new Map<string, import("./contradiction-judge.js").ContradictionJudgeResult>();
  const judgeResult = await judgeContradictionPairs(judgeInputs, config, localLlm, fallbackLlm, scanCache);
  log.info("[contradiction-scan] judge completed: %d judged, %d cached in %dms", judgeResult.judged, judgeResult.cached, judgeResult.elapsed);

  // 7. Write to review queue
  const queueEntries: Array<Omit<ContradictionPair, "pairId"> & { memoryIds: [string, string] }> = [];
  for (const [key, result] of judgeResult.results) {
    queueEntries.push({
      memoryIds: [result.memoryIdA, result.memoryIdB],
      verdict: result.verdict,
      rationale: result.rationale,
      confidence: result.confidence,
      detectedAt: new Date().toISOString(),
      // Set lastReviewedAt for non-actionable verdicts so cooldown prevents re-judging
      lastReviewedAt: result.verdict === "independent" ? new Date().toISOString() : undefined,
      namespace,
    });
  }

  const written = writePairs(memoryDir, queueEntries, { cooldownDays: scanConfig.cooldownDays });
  const elapsed = Date.now() - startTime;
  log.info("[contradiction-scan] complete: %d queued in %dms", written.length, elapsed);

  return {
    scanned: memories.length,
    candidates: candidates.pairs.length,
    judged: judgeResult.judged,
    queued: written.length,
    cooledDown,
    elapsedMs: elapsed,
  };
}

// ── Pair generation ────────────────────────────────────────────────────────────

interface CandidatePair {
  idA: string;
  idB: string;
  textA: string;
  textB: string;
  categoryA?: string;
  categoryB?: string;
}

interface PairGenResult {
  pairs: CandidatePair[];
  skipped: number;
}

async function generatePairs(
  memories: MemoryFile[],
  existingPairs: Map<string, ContradictionPair>,
  scanConfig: PluginConfig["contradictionScan"],
  embeddingLookup?: SemanticDedupLookup,
): Promise<PairGenResult> {
  const pairs: CandidatePair[] = [];
  const embeddingPairs: CandidatePair[] = [];
  let skipped = 0;
  const seen = new Set<string>();

  // Build index by entityRef for fast lookup
  const byEntity = new Map<string, MemoryFile[]>();
  for (const mem of memories) {
    const entity = mem.frontmatter.entityRef;
    if (entity) {
      const existing = byEntity.get(entity) ?? [];
      existing.push(mem);
      byEntity.set(entity, existing);
    }
  }

  // Strategy 1: Entity-ref based pairing (high precision)
  for (const [, group] of byEntity) {
    if (group.length < 2) continue;
    for (let i = 0; i < group.length; i++) {
      for (let j = i + 1; j < group.length; j++) {
        const a = group[i];
        const b = group[j];
        const pairId = computePairId(a.frontmatter.id!, b.frontmatter.id!);

        if (seen.has(pairId)) continue;
        seen.add(pairId);

        // Check cooldown
        const existing = existingPairs.get(pairId);
        if (existing && isCoolingDown(existing, scanConfig.cooldownDays)) {
          skipped++;
          continue;
        }

        pairs.push({
          idA: a.frontmatter.id!,
          idB: b.frontmatter.id!,
          textA: a.content,
          textB: b.content,
          categoryA: a.frontmatter.category as string | undefined,
          categoryB: b.frontmatter.category as string | undefined,
        });
      }
    }
  }

  // Strategy 2: Tag/topic overlap for memories without shared entityRef
  const noEntity = memories.filter((m) => !m.frontmatter.entityRef);
  for (let i = 0; i < noEntity.length; i++) {
    for (let j = i + 1; j < noEntity.length; j++) {
      const a = noEntity[i];
      const b = noEntity[j];
      const overlap = jaccardOverlap(
        (a.frontmatter.tags as string[]) ?? [],
        (b.frontmatter.tags as string[]) ?? [],
      );

      if (overlap < scanConfig.topicOverlapFloor) continue;

      const pairId = computePairId(a.frontmatter.id!, b.frontmatter.id!);
      if (seen.has(pairId)) continue;
      seen.add(pairId);

      const existing = existingPairs.get(pairId);
      if (existing && isCoolingDown(existing, scanConfig.cooldownDays)) {
        skipped++;
        continue;
      }

      pairs.push({
        idA: a.frontmatter.id!,
        idB: b.frontmatter.id!,
        textA: a.content,
        textB: b.content,
        categoryA: a.frontmatter.category as string | undefined,
        categoryB: b.frontmatter.category as string | undefined,
      });
    }
  }

  // Strategy 3: Embedding cosine similarity (enforces similarityFloor config)
  if (embeddingLookup) {
    const memoryById = new Map(memories.map((m) => [m.frontmatter.id!, m]));
    for (const mem of memories) {
      const id = mem.frontmatter.id!;
      try {
        const hits = await embeddingLookup(mem.content, 20);
        for (const hit of hits) {
          if (hit.score < scanConfig.similarityFloor) continue;
          if (hit.id === id) continue;
          const peer = memoryById.get(hit.id);
          if (!peer) continue;

          const pairId = computePairId(id, hit.id);
          if (seen.has(pairId)) continue;
          seen.add(pairId);

          const existing = existingPairs.get(pairId);
          if (existing && isCoolingDown(existing, scanConfig.cooldownDays)) {
            skipped++;
            continue;
          }

          embeddingPairs.push({
            idA: id,
            idB: hit.id,
            textA: mem.content,
            textB: peer.content,
            categoryA: mem.frontmatter.category as string | undefined,
            categoryB: peer.frontmatter.category as string | undefined,
          });
        }
      } catch {
        // Embedding backend unavailable — skip, entity-ref/tag strategies already covered
      }
    }
  }

  // Append embedding pairs after high-precision entity/topic pairs so the
  // downstream sort+slice(maxPairsPerRun) keeps precision-first ordering.
  pairs.push(...embeddingPairs);

  return { pairs, skipped };
}

// ── Helpers ────────────────────────────────────────────────────────────────────

async function loadEligibleMemories(storage: StorageManager, namespace?: string): Promise<MemoryFile[]> {
  let all: MemoryFile[];
  try {
    all = await storage.readAllMemories();
  } catch {
    return [];
  }

  return all.filter((mem) => {
    const fm = mem.frontmatter;
    // Only active memories (rule 53: explicit ACTIVE_STATUSES set)
    const status = (fm.status as MemoryStatus) ?? "active";
    if (!ACTIVE_STATUSES.has(status)) return false;

    // Only scan high-value categories
    const category = fm.category as string | undefined;
    if (category && !SCAN_CATEGORIES.has(category)) return false;

    // Must have content
    if (!mem.content || mem.content.trim().length === 0) return false;

    // Must have an ID
    if (!fm.id) return false;

    // Namespace scoping is handled at the storage layer — memoryDir is
    // already namespace-scoped, so readAllMemories() returns only memories
    // within the requested namespace.

    return true;
  });
}

function jaccardOverlap(a: string[], b: string[]): number {
  if (a.length === 0 && b.length === 0) return 0;
  const setA = new Set(a.map((t) => t.toLowerCase()));
  const setB = new Set(b.map((t) => t.toLowerCase()));
  let intersection = 0;
  for (const item of setA) {
    if (setB.has(item)) intersection++;
  }
  const union = setA.size + setB.size - intersection;
  return union === 0 ? 0 : intersection / union;
}
